# Generated by Django 5.2.11 on 2026-02-23 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Наименование")),
                ("description", models.TextField(verbose_name="Описание")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Действует"), ("deleted", "Удалён")],
                        default="active",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("image_key", models.CharField(blank=True, max_length=100, null=True, verbose_name="Ключ изображения")),
                ("video_key", models.CharField(blank=True, max_length=100, null=True, verbose_name="Ключ видео")),
                ("category", models.CharField(max_length=50, verbose_name="Категория")),
                ("manufacturer", models.CharField(blank=True, max_length=100, verbose_name="Производитель")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "db_table": "services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False, verbose_name="ID заявки")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("deleted", "Удалён"),
                            ("formed", "Сформирован"),
                            ("completed", "Завершён"),
                            ("rejected", "Отклонён"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("formed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата формирования")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата завершения")),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Итого")),
                ("items_count", models.IntegerField(default=0, verbose_name="Количество услуг")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Модератор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Телефон")),
                ("company", models.CharField(blank=True, max_length=100, verbose_name="Компания")),
                ("position", models.CharField(blank=True, max_length=100, verbose_name="Должность")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(default=1, verbose_name="Количество")),
                ("position", models.IntegerField(default=0, verbose_name="Позиция")),
                ("is_main", models.BooleanField(default=False, verbose_name="Главная услуга")),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Подытог")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.order", verbose_name="Заявка"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.service", verbose_name="Услуга"
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заявки",
                "verbose_name_plural": "Позиции заявки",
                "db_table": "order_items",
                "ordering": ["position"],
                "unique_together": {("order", "service")},
            },
        ),
    ]
