# Generated by Django 5.2.11 on 2026-02-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_orderitem_subtotal"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image_key_2",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Доп. фото 2"),
        ),
        migrations.AddField(
            model_name="service",
            name="image_key_3",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Доп. фото 3"),
        ),
        migrations.AddField(
            model_name="service",
            name="image_key_4",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Доп. фото 4"),
        ),
        migrations.AddField(
            model_name="service",
            name="image_key_5",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Доп. фото 5"),
        ),
    ]
